### ISSUE TITLE
Fumos duo causes exception

### ISSUE THREAD

**Issue by Slord6** [Azami7/Ollivanders2#106]
Casting "fumos duo" causes the following console output:

`[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:55)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:48:35 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:48:35 WARN]: java.lang.IllegalArgumentException: Wrong kind of data for this effect!
[20:48:35 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:843)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:838)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.Spell.SpellProjectile.move(SpellProjectile.java:111)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.Spell.FumosSuper.checkEffect(FumosSuper.java:46)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.projectileSched(OllivandersSchedule.java:93)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:55)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:48:35 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:48:35 WARN]: java.lang.IllegalArgumentException: Wrong kind of data for this effect!
[20:48:35 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:843)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:838)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.Spell.SpellProjectile.move(SpellProjectile.java:111)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.Spell.FumosSuper.checkEffect(FumosSuper.java:46)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.projectileSched(OllivandersSchedule.java:93)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:55)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:48:35 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:48:35 WARN]: java.lang.IllegalArgumentException: Wrong kind of data for this effect!
[20:48:35 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:843)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:838)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.Spell.SpellProjectile.move(SpellProjectile.java:111)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.Spell.FumosSuper.checkEffect(FumosSuper.java:46)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.projectileSched(OllivandersSchedule.java:93)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:55)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:48:35 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:48:35 WARN]: java.lang.IllegalArgumentException: Wrong kind of data for this effect!
[20:48:35 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:843)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:838)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.Spell.SpellProjectile.move(SpellProjectile.java:111)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.Spell.FumosSuper.checkEffect(FumosSuper.java:46)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.projectileSched(OllivandersSchedule.java:93)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:55)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:48:35 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:48:35 WARN]: java.lang.IllegalArgumentException: Wrong kind of data for this effect!
[20:48:35 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:843)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:838)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.Spell.SpellProjectile.move(SpellProjectile.java:111)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.Spell.FumosSuper.checkEffect(FumosSuper.java:46)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.projectileSched(OllivandersSchedule.java:93)
[20:48:35 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:55)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:48:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:48:35 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)`

The key portion appears to be 

> [20:53:14 WARN]: java.lang.IllegalArgumentException: Wrong kind of data for this effect!
> [20:53:14 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
> [20:53:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:843)
> [20:53:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.playEffect(CraftWorld.java:838)
> [20:53:14 WARN]:        at net.pottercraft.Ollivanders2.Spell.SpellProjectile.move(SpellProjectile.java:111)
> [20:53:14 WARN]:        at net.pottercraft.Ollivanders2.Spell.FumosSuper.checkEffect(FumosSuper.java:46)
> [20:53:14 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.projectileSched(OllivandersSchedule.java:93)
> [20:53:14 WARN]:        at net.pottercraft.Ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:55)
> [20:53:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
> [20:53:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
> [20:53:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
> [20:53:14 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
> [20:53:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
> [20:53:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
> [20:53:14 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Azami7** [comment]
What version of Ollivanders are you running? This is fixed in 2.2.5.2.

**Comment by Azami7** [comment]
Fix released with 2.2.6
