### ISSUE TITLE
Not Working ._.

### ISSUE THREAD

**Issue by Moonmanfx** [Azami7/Ollivanders2#111]
Here is what came out of the console 

[18:09:40 WARN]: [Ollivanders2] Task #2 for Ollivanders2 v2.2.6 generated an exception
java.lang.NullPointerException
	at net.pottercraft.Ollivanders2.Ollivanders2.getO2Player(Ollivanders2.java:1106) ~[?:?]
	at net.pottercraft.Ollivanders2.OllivandersSchedule.invisPlayer(OllivandersSchedule.java:285) ~[?:?]
	at net.pottercraft.Ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:72) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
[18:09:40 WARN]: [Ollivanders2] Task #2 for Ollivanders2 v2.2.6 generated an exception
java.lang.NullPointerException
	at net.pottercraft.Ollivanders2.Ollivanders2.getO2Player(Ollivanders2.java:1106) ~[?:?]
	at net.pottercraft.Ollivanders2.OllivandersSchedule.invisPlayer(OllivandersSchedule.java:285) ~[?:?]
	at net.pottercraft.Ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:72) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
[18:09:40 WARN]: [Ollivanders2] Task #2 for Ollivanders2 v2.2.6 generated an exception

**Comment by Azami7** [comment]
I am not sure which version of 1106 you were using so I am not sure where the NPE in getO2Player happened. Without knowing more about what was going on otherwise on your server at the time, there is not much I can do with just a stack trace.

It looks like someone may have been using invisibility? If you can send more information that would help.

**Comment by Azami7** [comment]
Hi there, a new version of the plugin is available - https://www.spigotmc.org/resources/ollivanders2.38992/update?update=240979

You may want to give this a try and see if you still get that error. If so, can you send us a new stack trace and the version of MC you are running?
