### ISSUE TITLE
Crash on entering text into chat

### ISSUE THREAD

**Issue by Slord6** [Azami7/Ollivanders2#2]
Hi! 

I'm using Ollivanders2 with with spigot (CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) and have found the plugin crashes when a message is sent in chat. (It may be worth noting the /okit command completes by giving the player all the items but the spells I've tested have all failed to work). I get the following output in the console when I send any message in chat:

```
[20:40:02 ERROR]: Could not pass event AsyncPlayerChatEvent to Ollivanders2 v2.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1276) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1214) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at net.pottercraft.Ollivanders2.Ollivanders2.checkForStationary(Ollivanders2.java:574) ~[?:?]
        at net.pottercraft.Ollivanders2.OllivandersListener.onPlayerChat(OllivandersListener.java:245) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        ... 11 more
[20:40:02 INFO]: <SamLord6> a
[20:40:06 INFO]: SamLord6 lost connection: Disconnected
[20:40:06 INFO]: SamLord6 left the game
[20:40:26 INFO]: /127.0.0.1:53755 lost connection: Disconnected
```

I've taken a cursory look at the code to see if anything screamed an answer but I've no experience with modding minecraft and I'm rusty with my Java so hope someone can help me out. I'm happy to contribute changes if someone can point me in the right direction. Thanks!

**Comment by Azami7** [comment]
Hi Slord6, sorry for the long delay in replying.

I have not seen that error before and we were also running 1.11.2 for several months.  We have made a few changes to the plugin so you might try grabbing the latest and see if that addresses it.  If not, let me know and we might be able to see if we can repro this on our test server.

**Comment by Azami7** [comment]
Closing this as resolved since we have not been able to duplicate this and no reply has been made by the submitter since May.

**Comment by Slord6** [comment]
For completeness:
Just tested and confirmed that this is fixed in the most recent version on a clean install.

Thanks!
