### ISSUE TITLE
Not creating Classes and upgraded spells not working

### ISSUE THREAD

**Issue by Plantsage** [Azami7/Ollivanders2#354]
When using spells like Mucus Ad Nauseam they pass through and keep going. Running debug shows that it isn't creating classes. Also spells like Incendio Tria and Lumos Maxima only detect the first word.  Tried on both Spigot and Paper, 1.16.5, Java 11 JDK or Java 15.

[16:25:31 WARN]: Failed to create class for MUCUS
[16:25:31 WARN]: java.lang.NoSuchMethodException: net.pottercraft.ollivanders2.effect.MUCUS.<init>(net.pottercraft.ollivanders2.Ollivanders2,java.lang.Integer,java.util.UUID)
[16:25:31 WARN]: 	at java.base/java.lang.Class.getConstructor0(Class.java:3508)
[16:25:31 WARN]: 	at java.base/java.lang.Class.getConstructor(Class.java:2244)
[16:25:31 WARN]: 	at net.pottercraft.ollivanders2.spell.AddO2Effect.addEffectsToTarget(AddO2Effect.java:161)
[16:25:31 WARN]: 	at net.pottercraft.ollivanders2.spell.AddO2Effect.doCheckEffect(AddO2Effect.java:126)
[16:25:31 WARN]: 	at net.pottercraft.ollivanders2.spell.O2Spell.checkEffect(O2Spell.java:254)
[16:25:31 WARN]: 	at net.pottercraft.ollivanders2.OllivandersSchedule.projectileSched(OllivandersSchedule.java:92)
[16:25:31 WARN]: 	at net.pottercraft.ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:55)
[16:25:31 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[16:25:31 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[16:25:31 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294)
[16:25:31 WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[16:25:31 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
[16:25:31 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[16:25:31 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[16:25:31 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by Azami7** [comment]
The issue with Mucus Ad Nauseam I was able to repro - looks like a recent change broke some reflection. Lumos Maxima and Incendio Tria are a different bug - they are being interpreted at the base spell Lumos and Incendio. Totally unrelated to the Mucus Ad Nauseam issue.

Working on quick fixes for both.

**Comment by Plantsage** [comment]
Thanks, I made a list of spells that have an issue.

      - Levicorpus
      - Mucus ad Nauseam
      - Lumos Duo
      - Lumos Solem
      - Draconifors
      - Carpe Retractum
      - Depulso
      - Incendio Duo
      - Incendio Tria
      - Flipendo
      - Glacius Duo
      - Glacius Tria
      - Loquela Ineptias
      - Accio
      - Ebublio
      - Reducto
      - Protego Maxima
      - Alarte Ascendare
      - Mortuos Suscitate
      - Praepando
      - Vento Folio
All these have class creation failure except for the Duo/Tria/Maxima/Solem spells and Draconifors with throws a task #9 Error. All other spells work as intended. Thanks for your work this mod is really great!

**Comment by Azami7** [comment]
See if this fixes the issues you are seeing:

https://pottercraft.s3-us-west-2.amazonaws.com/Ollivanders2/Ollivanders2-2.6-alpha-2.jar

**Comment by Azami7** [comment]
I should add, I was not able to repro issues with Draconifors and a few others but I tested them after I made the fixes for the others so maybe it was related. Let me know if you still see issues with those.

**Comment by Plantsage** [comment]
That seems to have fixed all the issues including Draconifors! Thanks alot!
