### ISSUE TITLE
Geminio item with malformed lore can cause an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Azami7** [Azami7/Ollivanders2#380]
From Discord:

14.06 22:05:03 [Server] WARN Task #3472 for Ollivanders2 v2.6 generated an exception
14.06 22:05:03 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
14.06 22:05:03 [Server] INFO at net.pottercraft.ollivanders2.OllivandersSchedule.geminio(OllivandersSchedule.java:200) ~[?:?]
14.06 22:05:03 [Server] INFO at net.pottercraft.ollivanders2.OllivandersSchedule.itemCurseSched(OllivandersSchedule.java:153) ~[?:?]
14.06 22:05:04 [Multicraft] Skipped 243 lines due to rate limit (30/s)
14.06 22:05:04 [Server] WARN Task #3472 for Ollivanders2 v2.6 generated an exception
14.06 22:05:04 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
14.06 22:05:04 [Server] INFO at net.pottercraft.ollivanders2.OllivandersSchedule.geminio(OllivandersSchedule.java:200) ~[?:?]
14.06 22:05:04 [Server] INFO at net.pottercraft.ollivanders2.OllivandersSchedule.itemCurseSched(OllivandersSchedule.java:153) ~[?:?]
14.06 22:05:04 [Server] INFO at net.pottercraft.ollivanders2.OllivandersSchedule.run(OllivandersSchedule.java:70) ~[?:?]
14.06 22:05:04 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-545]
14.06 22:05:04 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-545]
14.06 22:05:04 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1301) ~[patched_1.16.5.jar:git-Paper-545]
14.06 22:05:04 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[patched_1.16.5.jar:git-Paper-545]

14.06 22:14:30 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: null
14.06 22:14:30 [Server] INFO checking WG flag StateFlag{name='pvp'}
14.06 22:14:30 [Server] INFO No regions defined here.
14.06 22:14:30 [Server] INFO canTransfigure: PLAYER
14.06 22:14:30 [Server] INFO Failed success check.

**Comment by Azami7** [comment]
Added a guard for this issue.
