### ISSUE TITLE
Owl Post needs to me made async thread safe

### ISSUE THREAD

**Issue by Azami7** [Azami7/Ollivanders2#384]
```
[11:57:51] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to Ollivanders2 v2.6.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:1858) [spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1796) [spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1734) [spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.AbstractListenerPlayInImpl.a(AbstractListenerPlayInImpl.java:98) [Denizen-1.1.8-b1721-REL.jar:?]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:43) [spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalStateException: Asynchronous Chunk remove entity!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:407) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.WorldServer.chunkCheck(WorldServer.java:839) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.Entity.setPosition(Entity.java:437) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.Entity.f(Entity.java:1319) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at net.minecraft.server.v1_16_R3.Entity.setLocation(Entity.java:1305) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:497) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:525) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:475) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	at net.pottercraft.ollivanders2.OllivandersListener.owlPost(OllivandersListener.java:699) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3096-Spigot-9fb885e-296df56]
	... 13 more
```

**Comment by Azami7** [comment]
Owl post needs a refresh. There is no reason both players have to be online and the "owl" should return to its original location. We can also make the owl entity configurable.

Related to https://github.com/Azami7/Ollivanders2/issues/318
