### ISSUE TITLE
Reparo stack trace

### ISSUE THREAD

**Issue by Azami7** [Azami7/Ollivanders2#436]
Reported on Slack

1. Reparo stack trace:
````
[18:55:45 WARN]: java.lang.NoSuchMethodException: net.pottercraft.ollivanders2.spell.REPARO.<init>()
[18:55:45 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3349)
[18:55:45 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2151)
[18:55:45 WARN]:        at net.pottercraft.ollivanders2.player.O2Player.setSpellRecentCastTime(O2Player.java:512)
[18:55:45 WARN]:        at net.pottercraft.ollivanders2.listeners.OllivandersListener.castSpell(OllivandersListener.java:428)
[18:55:45 WARN]:        at net.pottercraft.ollivanders2.listeners.OllivandersListener.primaryHandInteractEvents(OllivandersListener.java:506)
[18:55:45 WARN]:        at net.pottercraft.ollivanders2.listeners.OllivandersListener$2.run(OllivandersListener.java:466)
[18:55:45 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[18:55:45 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485)
[18:55:45 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427)
[18:55:45 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[18:55:45 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
[18:55:45 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
[18:55:45 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:55:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
````

**Comment by Azami7** [comment]
Not able to reproduce this error after many tries of casting Reparo. Asked submitter for more information.
